name: modas_sophie
description: Control de tienda Modas Sophie
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_modas_sophie.png
